spring:
  application:
    name: TBTest
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://
    username:
    password:
    pool: 10
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      globally_quoted_identifiers: true
      ddl-auto: update
  profiles:
    include:
      - textholder

logging:
  file:
    name: log.log

bot:
  name:
  token:

