text:
  start:
    ua: "Ласкаво просимо, %s, до боту, котрий допоможе вам рандомно обирати заздалегідь в нього додані завдання/фільми/страви,
        в загалом будь що, на що у вас вистачить фантазії :)"
  createroom:
    ua: "Вітаю, ви створили кімнату № %d, перед початком незабудьте додати запис:)"
  joinroom:
    ua: "Введіть номер кімнати:"
  roomnotfound:
    ua: "Кімната не знайдена"
  joincomplicte:
    ua: "Вітаю, ви приєдналися до кімнати № %d, ви можете додати запис, або розпочати гру:)"
  createrow:
    ua: "Введіть ваш запис:"
  rowadded:
    ua: "Запис додано"
  unknowncommand:
    ua: "Невідома команда, оберіть команду з меню"
  notatext:
    ua: "Бот процює лише з текстовими повідомленнями"
  norow:
    ua: "Записів не існує, додайте запис"
  main:
    ua: "Головне меню"
  startmenu:
    ua: "Оберіть неохідну кімнату"


menu:
  create:
    ua: "Створити нову кімнату"
  join:
    ua: "Приєднатися до існуючої"
  added:
    ua: "Додати запис"
  startgame:
    ua: "Розпочати підбір"
  nextrow:
    ua: "Наступний"
  finishgame:
    ua: "Завершити"
  tostart:
    ua: "До вибору кімнат"



